--- #YAML:1.0
name: CGI-Session-DB2
version: 0.01
author:
  - Darin McBride <dmcbride@cpan.org>
abstract: DB2 driver for CGI::Session
license: perl
requires:
  CGI::Session: 3.95
  DB2::db: 0.19
  perl: 5.8.0
provides:
  CGI::Session::DB2:
    file: lib/CGI/Session/DB2.pm
    version: 0.01
  CGI::Session::DB2::Cgisess:
    file: lib/CGI/Session/DB2.pm
    version: 0.01
  CGI::Session::DB2::db:
    file: lib/CGI/Session/DB2.pm
    version: 0.01
generated_by: Module::Build version 0.24
